-- VehicleLink
-- Dev reset: drop tables (use with caution)
-- Generated by splitting init.sql
-- MySQL 8+

-- NOTE: These scripts assume you have already created and selected your database.
-- Example:
--   CREATE DATABASE IF NOT EXISTS vehiclelink;
--   USE vehiclelink;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS lot_spaces;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS makes;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS part_categories;

SET FOREIGN_KEY_CHECKS = 1;
