-- VehicleLink
-- Migration: schema (tables, constraints)
-- Generated by splitting init.sql into migration + seed
-- MySQL 8+

-- NOTE: These scripts assume you have already created and selected your database.
-- Example:
--   CREATE DATABASE IF NOT EXISTS vehiclelink;
--   USE vehiclelink;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ===============
-- Tables
-- ===============

CREATE TABLE makes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_makes_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE models (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  make_id INT UNSIGNED NOT NULL,
  name VARCHAR(80) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_models_make_name (make_id, name),
  CONSTRAINT fk_models_make
    FOREIGN KEY (make_id) REFERENCES makes(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE lot_spaces (
  code VARCHAR(4) NOT NULL,
  PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE vehicles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  year SMALLINT UNSIGNED NOT NULL,
  model_id INT UNSIGNED NOT NULL,
  color VARCHAR(30) NULL,
  odometer INT UNSIGNED NULL,
  vin CHAR(17) NOT NULL,
  date_received DATE NOT NULL,
  picture_folder VARCHAR(255) NULL,
  lot_space_code VARCHAR(4) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_vehicles_vin (vin),
  UNIQUE KEY uq_vehicles_lot_space (lot_space_code),
  KEY idx_vehicles_year (year),
  KEY idx_vehicles_model (model_id),
  CONSTRAINT fk_vehicles_model
    FOREIGN KEY (model_id) REFERENCES models(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_vehicles_lot_space
    FOREIGN KEY (lot_space_code) REFERENCES lot_spaces(code)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE part_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_part_categories_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE parts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  part_category_id INT UNSIGNED NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_parts_category_name (part_category_id, name),
  KEY idx_parts_category (part_category_id),
  CONSTRAINT fk_parts_category
    FOREIGN KEY (part_category_id) REFERENCES part_categories(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
