import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header className="z-999"/>
        <div className="h-[110px] sm:h-[125px] md:h-[150px] lg:h-[175px] xl:h-[235px] fixed top-0 w-full bg-primaryBackground z-990"></div>
        <div className="mb-[110px] sm:mb-[125px] md:mb-[150px] lg:mb-[175px] xl:mb-[235px]"></div>
        {children}
        <Footer className="text-footerText bg-footerBackground"/>
      </body>
    </html>
  );
}
